### PR TITLE
Update cs.po

### PR DESCRIPTION
**Pull request by lev741**
Translation issue. This string can`t be translated located on profile 2:
GNOME 40+ - Bottom Hot Edge

### CODE REVIEW

**Comment by G-dH** [comment]
Is problem the source string or is it the translation?

**Comment by lev741** [comment]
I didn`t found the string.

**Comment by G-dH** [comment]
I changed the profile name, I hope it helps.

**Comment by lev741** [comment]
It should be fixed. You can merge translation.
Will see. :)

**Comment by G-dH** [comment]
@lev741 The strings containing % were still a problem. I've changed all affected strings in the `prefs.js` and updated your translation. Let me know how it works for you. Thanks.

**Pull request merged**
